company_profile/urls.py
from django.urls import path
from .views import profile, add_testimony

app_name = 'company_profile'

urlpatterns = [
    path('', profile, name='profile'),
    path('add-testimony', add_testimony, name='add-testimony'),
]

news/urls.py
from django.urls import path
from .views import news_detail, news_list

app_name = 'news'


urlpatterns = [
	path('', news_list, name="news_list"),
	path('<int:news_id>/detail/', news_detail, name='news_detail'),
]

ui_student_union/urls.py
from django.contrib import admin
from django.urls import path, include
from hello.views import hello_page, search_result
from user_auth.views import hello_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', hello_page),
    path('hello', hello_user),
    path('accounts/', include('user_auth.urls', namespace='user_auth')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls', namespace="news")),
    path('events/', include('events.urls', namespace='events')),
    path('event/', include('event_regist.urls', namespace='event')),
    path('search/', search_result, name='search-event'),
    path('user_events/', include('user_events.urls', namespace='user_events')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('profile/', include('company_profile.urls', namespace='profile')),
]

company_profile/models.py
from django.conf import settings
from django.db import models


class Testimony(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    testimony = models.TextField()

    class Meta:
        verbose_name_plural = 'Testimonies'

    def __str__(self):  # pragma: no cover
        return self.testimony

company_profile/forms.py
from django import forms

from .models import Testimony


class TestimonyForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TestimonyForm, self).__init__(*args, **kwargs)

        testimony_field = self.fields['testimony']
        testimony_field.label = ''
        testimony_field.required = True
        testimony_field.error_messages = {
            'required': 'Testimoni harus diisi.'
        }
        testimony_field.widget = forms.Textarea(
            attrs={
                'placeholder': 'Say something about us',
                'class': 'form-control',
            }
        )

    class Meta:
        model = Testimony
        fields = ['testimony']

company_profile/views.py
import json

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import TestimonyForm
from .models import Testimony

response = {}


def profile(request):
    if request.user.is_authenticated:
        response['form'] = TestimonyForm()
    testimonies = Testimony.objects.all().order_by('id').reverse()[:8]
    response['testimonies'] = testimonies
    return render(request, 'profile.html', response)


def add_testimony(request):
    data = {}
    if request.method == 'POST' and request.user.is_authenticated:
        testimony_form = TestimonyForm(data={
            'testimony': request.POST['testimony'],
        })
        user = request.user
        if testimony_form.is_valid():
            new_testimony = testimony_form.save(commit=False)
            new_testimony.user = user
            new_testimony.save()
            data['log'] = {'user': new_testimony.user.username, 'testimony': new_testimony.testimony}
            data['success'] = True
            json_data = json.dumps(data)
        else:
            errors = dict([
                (key, [error for error in value]) for key, value in testimony_form.errors.items()
            ])
            data['log'] = errors
            data['success'] = False
            json_data = json.dumps(data)
        return HttpResponse(json_data, content_type='application/json')
    else:
        return redirect('profile:profile')

company_profile/templates/profile.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>About Us</title>

    <style>
        #testimony-form {
            margin: auto;
            width: 30.5%;
            border-radius: 20px;
            padding-bottom: 20px;
        }

        #testimony-item {
            margin: auto;
            width: 40%;
        }

        .card-header {
            background: #5D5D5D;
        }

        .card-header span {
            color: white;
        }

        #submit-button {
            margin-top: 13px;
            padding: 8px 30px;
            background-color: #5D5D5D;
            color: white;
            border: 1px solid black;
            border-radius: 4px;
            cursor: pointer;
        }

        #submit-button:hover {
            background-color: #FDD831;
            color: black;
            border: 1px solid black;
        }

    </style>
</head>
<body>
    <header>
        {% include 'navbar.html' %}
    </header>

   <div class="jumbotron">
       <h1 class="display-3">About Us</h1>
       <hr class="my-4">
       <p class="lead font-weight-bold">We bring you the hottest events and news from our beloved campus!</p>
   </div>

    <div id="testimonies" class="container">
        <div class="row" id="testimony-rows">
            {% for item in testimonies %}
                <div id="testimony-item" class="card mb-3 text-center">
                    <div class="card-header">
                        <span>{{ item.user.username }}</span>
                    </div>
                    <div class="card-body">
                        <blockquote class="card-blockquote">
                            <p>{{ item.testimony }}</p>
                        </blockquote>
                    </div>
                </div>
        {% endfor %}
        </div>
    </div>

    {% if user.is_authenticated %}
            <div class="container-fluid">
                <form class="form-group" id="testimony-form" method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input id="submit-button" class="btn btn-dark" type="submit" value="Give Testimony">
                </form>
            </div>
    {% endif %}

    <footer>
        {% include 'footer.html' %}
    </footer>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="text/javascript">
        var csrfToken = jQuery("[name=csrfmiddlewaretoken]").val();
        var submitformURL = "{% url 'profile:add-testimony' %}";
    </script>
    <script src="{% static 'js/profile_script.js' %}"></script>
</body>
</html>