event_regist/urls.py
from django.urls import path

from .views import event_detail

app_name = 'event_regist'

urlpatterns = [
    path('<int:event_id>/detail/', event_detail, name='event-detail'),
]

events/urls.py
from django.urls import path
from . import views

app_name = 'events'
urlpatterns = [
    path('', views.index, name='index'),
]

news/urls.py
from django.urls import path
from .views import news_detail, news_list

app_name = 'news'


urlpatterns = [
	path('', news_list, name="news_list"),
	path('<int:news_id>/detail/', news_detail, name='news_detail'),
]

ui_student_union/urls.py
from django.contrib import admin
from django.urls import path, include
from hello.views import hello_page, search_result
from user_auth.views import hello_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', hello_page),
    path('hello', hello_user),
    path('accounts/', include('user_auth.urls', namespace='user_auth')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('news/', include('news.urls', namespace="news")),
    path('events/', include('events.urls', namespace='events')),
    path('event/', include('event_regist.urls', namespace='event')),
    path('search/', search_result, name='search-event'),
    path('user_events/', include('user_events.urls', namespace='user_events')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('profile/', include('company_profile.urls', namespace='profile')),
]

user_auth/urls.py
from django.urls import path

from .views import signup

app_name = 'user_auth'

urlpatterns = [
    path('signup/', signup, name='signup'),
]

user_events/urls.py
from django.urls import path
from . import views

app_name = 'user_events'
urlpatterns = [
    path('', views.user_events, name='user_events'),
    path('get-user-events', views.get_user_events_json, name='get-user-events')
]

templates/footer.html
<!DOCTYPE html>
<html>
<style>

    .footer-container{
        width:100%;
    }
    .bottom-footer{
        background-color: #5D5D5D;
        padding: 10px;
        color:#FBFBFB;
    }
    .bottom-footer-left{
        padding-left: 5vw;
        float:left;
        left: 0px;
        width: 50%;
        height: 100px;
        font-size:18px;
    }

    .bottom-footer-right{
        float:right;
        padding-right: 5vw;
        text-align: right;
        right: 0px;
        width: 50%;
        height: 100px;
        font-size: 18px;
    }

    .bottom-footer-lower{

        width: 100%;
        background-color: #404040;
        color:#C9C9C9;
        text-align: center;
        font-size: 14px;
    }
</style>

<body>
<!--FOOTER-->
    <div class="footer-container">
        <!-- left -->
            <div class= "bottom-footer-left bottom-footer">
                Contact Us<br>
                Phone : 1404xxxx <br>
                Email : uistudentunion@ui.ac.id
            </div>
            <!-- right -->
            <div class= "bottom-footer-right bottom-footer">
                Follow Us on Social Media <br>
                <img src="https://image.ibb.co/f09jkf/facebook.png" alt="facebook" height=60; width=60>
                <img src="https://image.ibb.co/kpiYd0/linkedin.png" alt="linkedin" height=60; width=60>
                <img src="https://image.ibb.co/ha3AQf/instagram.png" alt="instagram" height=60; width=60>
                &nbsp &nbsp
            </div>
            <!-- lower -->
            <div class="bottom-footer-lower">
                @ 2018 UI Student Union. All Rights Reserved
            </div>
    </div>
</body>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>UI-Student Union</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .coverimg {
            background-image: url("https://preview.ibb.co/kyyYGL/logo3.png");

            /* Full height */
            height: 100%;
            width: 100%;
            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }

        .bgimg {
            background-image: url("https://image.ibb.co/d52fvf/background.png");
            background-repeat: no-repeat;
        }
    </style>
</head>
<body>

    <header>{% include 'navbar.html' %}</header>

     <!--content-->
    <div class="coverimg">
        <br><br><br><br>

        <h1 style="text-align:center;text-shadow: 3px 3px #fdd730;font-size: 72px;
        font-weight:900;"> Welcome to </h1>

        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    </div>

    <div class="bgimg">
        <br><br><br>

        <h1 style="text-shadow: 3px 3px #fdd730; font-size: 50px; font-weight:900; padding-left:5vw;
        padding-top:1vw"> Upcoming Events </h1>

        <div class="w3-container"  style="padding-left:5vw; padding-right:5vw">
            {% if events %}
            {% for event in events %}
                <div class="w3-third" style="text-align:center">
                    <a href="{% url 'event_regist:event-detail' event_id=event.id %}">
                        <img src="{{ event.image }}" style="width:100%; height:auto">
                    </a>
                    Held by: {{ event.organizer }}
                    <br><br>
                    <strong>{{ event.title }}</strong><br>
                    "{{ event.headline }}"
                    <br><br>
                    <img src="https://image.ibb.co/gGg8BL/date.png" style="height:5vw; width:auto">
                    {{ event.date }}
                    <br><br>
                    <img src="https://image.ibb.co/enrarL/location.png" style="height:5vw; width:auto">
                    {{ event.place }}
                </div>
                {% endfor %}
            {% else %}
                <div class="w3-container" style=" text-align:center; padding:20vw">
                    <h1 style=" font-size: 30px; font-weight:900;">No Upcoming Events </h1>
                </div>
            {% endif %}
        </div>

        <br><br><br>
        <div style="float:right; padding-right:3vw">
            <a href="{% url 'events:index' %}">See More Events</a> <!--link ke page events -->
        </div>
        <br><br>
    </div>

    <div class="bgimg">
        <br><br><br>
        <!-- nanti news taro sini -->
        <h1 style="text-shadow: 3px 3px #fdd730; font-size: 50px; font-weight:900; padding-left:5vw;
        padding-top:1vw"> Latest News </h1><br><br>

        <div class="w3-container"  style="padding-left:5vw; padding-right:5vw">
            {% if news %}
                {% for news in news %}
                <div class="w3-third" style="text-align:left">
                    <a href="{% url 'news:news_detail' news_id=news.id %}">
                        <img src="{{ news.link_image }}" style="width:80%; height:auto"><br>
                    </a>
                    <strong style="font-size:27px">{{ news.judul }}</strong><br>
                    <small>{{ news.date_published }}</small>
                    <img src="https://image.ibb.co/chmx5f/bulat.png" style="width:10px; height:auto">
                    {{ news.author }}
                    <br>

                    "{{ news.headline }}"
                    <br><br>

                    <br><br>
                </div>
                {% endfor %}
            {% else %}
                <div class="w3-container" style=" text-align:center; padding:20vw">
                    <h1 style=" font-size: 30px; font-weight:900;"> No News </h1>
                </div>
            {% endif %}
        </div>
        <div style="float:right; padding-right:3vw">
            <a href="{% url 'news:news_list' %}">See More News</a> <!--link ke page events -->
        </div>
    </div>
    <br><br>

    <footer>
        {% include 'footer.html' %}
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<!doctype html>
<head>
    <style>
        body {
            background-image: url("https://image.ibb.co/d52fvf/background.png");
            background-repeat: no-repeat;
            margin: auto;
        }

        .bg-dark {
            background-color: #5D5D5D!important;
        }
    </style>
</head>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'events:index' %}">Events</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'news:news_list' %}">News</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_events:user_events' %}">Your Events</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile:profile' %}">About Us</a>
            </li>
        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto" href="/">UI Student Union</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">

            <form class="form-inline" action="{% url 'search-event' %}" method="GET" accept-charset="UTF-8">
                <button type="submit" style="margin-right: 10px">
                    <img src="https://image.ibb.co/g8Nn5f/search-bar.png" width="30px" height="30px">
                </button>
                <input class="form-control mr-sm-2" name="search" type="search" placeholder="Cari event" aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="https://image.ibb.co/hdOid0/profile.png" width="30px" height="30px">
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'logout' %}?next={{ request.path }}">Sign Out</a>
                    </div>
                </div>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Sign In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_auth:signup' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>